name: Deploy Vite site to GitHub Pages

on:
    push:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repo
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            # Setup Node
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            # Install dependencies
            - name: Install dependencies
              run: npm ci

            # Build Vite project
            - name: Build project
              run: npm run build

            # Setup GitHub Pages
            - name: Setup Pages
              uses: actions/configure-pages@v5

            # Upload dist folder
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v4
              with:
                  path: ./dist

            # Deploy
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
